<?php

namespace App;

use Kalnoy\Nestedset\NodeTrait;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    use NodeTrait;

    protected $fillable = ['name', 'slug'];

    public function getRouteKeyName()
    {
        return 'slug'; // TODO: Change the autogenerated stub
    }

    public function scopeWithListingsInArea($query, Area $area)
    {
        return $query->with(['listings' => function($q) use ($area) {
            $q->isLive()->inArea($area);
        }]);
    }

    public function listings()
    {
        return $this->hasMany(Listing::class);
    }
}
